# Generated by Django 5.0.4 on 2024-04-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0011_auto_20200609_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='returned_items',
            field=models.ManyToManyField(blank=True, to='gstbillingapp.invoice'),
        ),
    ]
