# Generated by Django 5.0.4 on 2024-04-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0012_invoice_returned_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='returned_items',
        ),
    ]
